----------- Job Table --------------------------
/*
DROP TABLE [dbo].[JOB]
*/
CREATE TABLE [dbo].[JOB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_GUID] [varchar](50) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[MOBILE_NUMBER] [varchar](50) NOT NULL,
	[STATUS] [int] NOT NULL,
	[CREATED_USER_ID] [varchar](50) NOT NULL,
	[CREATED_DATETIME] [datetime] NOT NULL,
	[UPDATED_USER_ID] [varchar](50) NOT NULL,
	[UPDATED_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_JOB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_JOB_GUID]   DEFAULT ('') FOR [JOB_GUID]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_NAME]   DEFAULT ('') FOR [NAME]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_MOBILE_NUMBER]   DEFAULT ('') FOR [MOBILE_NUMBER]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_STATUS]   DEFAULT (0) FOR [STATUS]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_CREATED_USER_ID]   DEFAULT ('System') FOR [CREATED_USER_ID]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_CREATED_DATETIME]    DEFAULT (getdate()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_UPDATED_USER_ID]   DEFAULT ('System') FOR [UPDATED_USER_ID]
GO

ALTER TABLE [dbo].[JOB] ADD  CONSTRAINT [DF_JOB_UPDATED_DATETIME]    DEFAULT (getdate()) FOR [UPDATED_DATETIME]
GO

/*
TRUNCATE TABLE [dbo].[JOB]
*/

/*
INSERT [dbo].[JOB](
	[JOB_GUID],
	[NAME],
	[MOBILE_NUMBER]
)
SELECT '4d60a220-cc93-4f3a-8ed3-5b986619e158', 'Create Order', '+6584816894'
UNION ALL
SELECT '6b5a1415-c963-4dc3-ae91-c7a535b24f3c', 'Dispatch Order', '+6584816894'
*/

/*
SELECT * FROM [dbo].[JOB]
*/



----------- Note Table --------------------------
/*
DROP TABLE [dbo].[NOTE]
*/
CREATE TABLE [dbo].[NOTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOTE_GUID] [varchar](50) NOT NULL,
	[JOB_GUID] [varchar](50) NOT NULL,
	[COMMENT] [varchar](max) NOT NULL,
	[CREATED_USER_ID] [varchar](50) NOT NULL,
	[CREATED_DATETIME] [datetime] NOT NULL,
	[UPDATED_USER_ID] [varchar](50) NOT NULL,
	[UPDATED_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_NOTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_NOTE_GUID]   DEFAULT ('') FOR [NOTE_GUID]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_JOB_GUID]   DEFAULT ('') FOR [JOB_GUID]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_COMMENT]   DEFAULT ('') FOR [COMMENT]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_CREATED_USER_ID]   DEFAULT ('System') FOR [CREATED_USER_ID]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_CREATED_DATETIME]    DEFAULT (getdate()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_UPDATED_USER_ID]   DEFAULT ('System') FOR [UPDATED_USER_ID]
GO

ALTER TABLE [dbo].[NOTE] ADD  CONSTRAINT [DF_NOTE_UPDATED_DATETIME]    DEFAULT (getdate()) FOR [UPDATED_DATETIME]
GO

/*
TRUNCATE TABLE [dbo].[NOTE]
*/

/*
INSERT [dbo].[NOTE](
	[NOTE_GUID],
	[JOB_GUID],
	[COMMENT]
)
SELECT 'b0f8f366-ce85-4e5c-86fc-00d71b11a04c', '4d60a220-cc93-4f3a-8ed3-5b986619e158', 'Completed'
UNION ALL
SELECT '28862202-5a1f-46d8-abf0-f50e6995246a', '4d60a220-cc93-4f3a-8ed3-5b986619e158', 'Completed'
UNION ALL
SELECT 'd75d0c78-c4ce-44a8-8df1-2e4e7c07ee8f', '6b5a1415-c963-4dc3-ae91-c7a535b24f3c', 'Completed'
*/

/*
SELECT * FROM [dbo].[NOTE]
*/
